//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public static class Util
{
	private static Plane gamePlane = new Plane (new Vector3 (0.0f, 1.0f, 0.0f), 0.0f);

	public static Vector3 MouseToWorld(){
		return ScreenToWorld(Input.mousePosition);
	}

	public static Vector3 ScreenToWorld(Vector2 screen){
		Ray ray = Camera.main.ScreenPointToRay (screen);
		float rayDistance;
		if (gamePlane.Raycast (ray, out rayDistance))
			return ray.GetPoint (rayDistance);
		return Vector3.zero;
	}

	public static Vector2 WorldToScreen(Vector3 world){
		return Camera.main.WorldToScreenPoint (world);
	}
	
	public static float InvertY(float y){
		return Screen.height - y;
	}
}